function data = prepare_data()
%PREPARE_DATA Load the CSVs once and flag the corrupted test images.
%   No pixel values are altered here. test_outlier marks the test images
%   that contain at least one pixel outside the stated [0,255] range, which
%   is the same flag cs1_mnist_evaluate_test_set.m plots.

[Xtrain, ytrain, Xtest, ytest] = load_mnist();

data = struct( ...
    'Xtrain', Xtrain, ...
    'ytrain', ytrain, ...
    'Xtest', Xtest, ...
    'ytest', ytest, ...
    'test_outlier', any(Xtest < 0 | Xtest > 255, 2));
end
