function rec = run_one(data, k, seed, init_method, dist_mode, max_iter)
%RUN_ONE Fit one k-means model and measure everything the report needs.
%   data is the struct returned by prepare_data(). rec is a scalar struct
%   whose fields become one row of the sweep table; rec.cost_curve holds the
%   per-iteration WCSS and is stored separately from the flat table.

fit = kmeans_core(data.Xtrain, k, seed, init_method, dist_mode, max_iter);
labels = label_centroids(data.Xtrain, fit.idx, data.ytrain, k, fit.centroids);

% Cluster occupancy.
counts = accumarray(fit.idx, 1, [k 1]);

% Training accuracy from the same assignments the fit produced.
train_pred = labels(fit.idx);
train_acc = mean(train_pred == data.ytrain);

% Test-time prediction, timed on its own because it is what a deployed
% classifier pays per image.
t0 = tic;
test_idx = assign_points(data.Xtest, fit.centroids, dist_mode);
predict_time = toc(t0);
test_pred = labels(test_idx);
correct = (test_pred == data.ytest);
test_acc = mean(correct);

% Same accuracy restricted to the test images whose pixels all lie in
% [0,255], so the corrupted images can be discussed separately.
clean = ~data.test_outlier;
test_acc_clean = mean(correct(clean));
outlier_correct = sum(correct(data.test_outlier));

rec = struct( ...
    'k', k, ...
    'seed', seed, ...
    'init_method', string(init_method), ...
    'dist_mode', string(dist_mode), ...
    'n_iter', fit.n_iter, ...
    'converged', double(fit.converged), ...
    'final_cost', fit.cost(end), ...
    'init_cost', fit.cost(1), ...
    'fit_time', fit.fit_time, ...
    'predict_time', predict_time, ...
    'train_acc', train_acc, ...
    'test_acc', test_acc, ...
    'test_acc_clean', test_acc_clean, ...
    'outlier_correct', outlier_correct, ...
    'n_outlier', sum(data.test_outlier), ...
    'n_empty', sum(counts == 0), ...
    'min_cluster', min(counts), ...
    'max_cluster', max(counts), ...
    'n_pure_clusters', count_pure(fit.idx, data.ytrain, k), ...
    'cost_curve', {fit.cost});
end

function n = count_pure(idx, y, k)
%COUNT_PURE Clusters whose members all share one digit label.
n = 0;
for j = 1:k
    members = y(idx == j);
    if ~isempty(members) && all(members == members(1))
        n = n + 1;
    end
end
end
