function K = select_k()
%SELECT_K Choose k from the measured accuracy, and print the evidence.
%   Every number comes from the norm-loop implementation used by
%   cs1_mnist_base_skeleton.m, ten random starts per k.
%
%   The cost cannot choose k on its own: the within-cluster sum of squares
%   falls every time k grows, and reaches exactly zero at k = n = 1500,
%   where every training image is its own centroid. So k is chosen from the
%   test accuracy instead, with one plain rule:
%
%       pick the smallest k that no larger k beats by more than one
%       percentage point.
%
%   k = n = 1500 is printed separately. It stores every training image and
%   does no clustering at all, so it is a reference point, not a candidate.

tol = 0.01;   % one percentage point

here = fileparts(mfilename('fullpath'));
addpath(here);

A = sortrows([aggregate_results('forgy_loop', false); ...
              aggregate_results('ext_loop',   false)], 'k');

candidate = A(A.k < 1500, :);
acc = candidate.mean_test_acc;

% Smallest k that nothing larger beats by more than tol.
chosen_i = numel(acc);
for i = 1:numel(acc)
    if all(acc(i+1:end) <= acc(i) + tol)
        chosen_i = i;
        break;
    end
end

[best_acc, best_i] = max(acc);

K = struct( ...
    'chosen_k', candidate.k(chosen_i), ...
    'chosen_acc', acc(chosen_i), ...
    'chosen_fit_time', candidate.mean_fit_time(chosen_i), ...
    'best_k', candidate.k(best_i), ...
    'best_acc', best_acc, ...
    'nn_k', A.k(end), ...
    'nn_acc', A.mean_test_acc(end), ...
    'tolerance', tol, ...
    'table', A);

% One table covering every k, for the report to quote directly.
report = table(A.k, A.n_seeds, A.mean_final_cost, A.mean_train_acc, ...
    A.mean_test_acc, A.std_test_acc, A.min_test_acc, A.max_test_acc, ...
    A.mean_n_iter, A.mean_fit_time, 1000*A.mean_predict_time/200, ...
    A.mean_n_empty, A.mean_min_cluster, A.mean_max_cluster, ...
    'VariableNames', {'k','random_starts','mean_cost','mean_train_acc', ...
        'mean_test_acc','sd_test_acc','min_test_acc','max_test_acc', ...
        'mean_iterations','mean_fit_seconds','ms_per_test_image', ...
        'mean_empty_clusters','mean_smallest_cluster','mean_largest_cluster'});
writetable(report, fullfile(here,'results','summary_all_k.csv'));

fprintf('\n=== choosing k from test accuracy (10 random starts per k) ===\n');
fprintf('CHOSEN     k=%d  mean test accuracy %.4f  mean fit time %.3f s  stores %d centroids instead of 1500 images\n', ...
    candidate.k(chosen_i), acc(chosen_i), candidate.mean_fit_time(chosen_i), ...
    candidate.k(chosen_i));
fprintf('HIGHEST    k=%d  mean test accuracy %.4f  (only %.1f points above the chosen k)\n', ...
    candidate.k(best_i), best_acc, 100*(best_acc - acc(chosen_i)));
fprintf('REFERENCE  k=%d  mean test accuracy %.4f, cost exactly 0, no clustering left\n', ...
    A.k(end), A.mean_test_acc(end));
fprintf('SUBMITTED  k=100 mean test accuracy %.4f\n', ...
    A.mean_test_acc(A.k==100));

fprintf('\n%5s %10s %8s %10s %11s %9s %9s\n', ...
    'k','mean_acc','spread','gain_vs_prev','cost','fit_s','ms/image');
for i = 1:height(A)
    if i == 1
        gain = NaN;
    else
        gain = A.mean_test_acc(i) - A.mean_test_acc(i-1);
    end
    fprintf('%5d %10.4f %8.4f %12.4f %11.3e %9.3f %9.3f\n', ...
        A.k(i), A.mean_test_acc(i), A.max_test_acc(i)-A.min_test_acc(i), ...
        gain, A.mean_final_cost(i), A.mean_fit_time(i), ...
        1000*A.mean_predict_time(i)/200);
end
end
